artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_urls:  https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
  local_data_files: artifacts/data_ingestion/data.zip # for dowinloading the data files
  unzip_dir: artifacts/data_ingestion
data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  required_file: ['train','validation','test']
data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail
model_trainer:
  root_dir: artifacts/data_trainer
  data_path: artifacts/data_transformation/samsum_dataset
  model_ckpt: goole/peagasus-cnn_dailymail
model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path : artifacts/data_transformation/samsum_dataset
  model_path : artifacts/model_trianer/pagasus-samsum-model
  tokenizer_path : artifacts/model_trainer/samsum_dataset
  metric_file_name : artifacts/model_evluation/metric.csv
